<?php

?>
<ul class="breadcrumb breadcrumb-page">
    <div class="breadcrumb-label text-light-gray">You are here: </div>
    <li><a href="/admin">Home</a></li>
    <li class="active"><a href="/admin">Video</a></li>
</ul>
<div class="page-header">

    <div class="row">
        <!-- Page header, center on small screens -->
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-video-camera page-header-icon"></i>&nbsp;&nbsp;Video</h1>
    </div>
</div> <!-- / .page-header -->
<div class="panel" id="sample-list">
    <div class="panel-heading">
        <span class="panel-title">List</span>
    </div>

    <div class="panel-body">
        <div class="table-primary table-responsive">
            <table class="table table-striped table-bordered" id="book-table">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Title</th>
                    <th>Link</th>
                    <th>Language</th>
                    <th>Category</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>

</div>
