<ul class="breadcrumb breadcrumb-page">
    <div class="breadcrumb-label text-light-gray">You are here: </div>
    <li><a href="/admin">Home</a></li>
    <li class="active"><a href="/admin/userClass">User class</a></li>
</ul>
<div class="page-header">

    <div class="row">
        <!-- Page header, center on small screens -->
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-pencil page-header-icon"></i>&nbsp;&nbsp;User class</h1>
    </div>
</div> <!-- / .page-header -->
<div class="panel" id="sample-list">
    <div class="panel-heading">
        <span class="panel-title">List</span>
    </div>

    <div class="panel-body">
        <div class="table-primary table-responsive">
            <table class="table table-striped table-bordered" id="userclass-table">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Title</th>
                    <th>Language</th>
                    <th>Category</th>
                    <th>Level</th>
                    <th>Created User</th>
                    <th>Created Date</th>
                    <th>Uploaded by</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php $page_count = count($page->items); ?>
                <?php foreach($page->items as $key=>$val) : /** @var $val Classroom */?>
                    <tr>
                        <td><?php echo $page->total_items - $key - (($page->current-1) * $limit);  ?></td>
                        <td><?php echo $val->title; ?></td>
                        <td><?php echo $val->getLanguage(); ?></td>
                        <td><?php echo $val->getInterest(); ?></td>
                        <td><?php echo $val->level; ?></td>
                        <td><?php echo $val->getUser()->nickname; ?></td>
                        <td><?php echo date('m-d-Y', $val->created_at); ?></td>
                        <td>
                            <?php if($val->getUser()->is_admin == 1) :?>
                                Admin
                            <?php else : ?>
                                User
                            <?php endif ?>
                        </td>
                        <td class="text-left" style="width:200px;">
                            <a href="/learn/class/<?php echo $val->classroom_id; ?>" class="btn btn-default btn-xs" target="_blank" >View</a>
<!--                            --><?php //if($val->sample_id == 0) :?>
                                <?php if($val->is_confirmed) : ?>
                                    <button type="button" class="btn btn-primary btn-xs btn-approve" data-classroom-id="<?php echo $val->classroom_id; ?>">Approve</button>
                                <?php else : ?>
                                    <button type="button" class="btn btn-default btn-xs btn-approve" data-classroom-id="<?php echo $val->classroom_id; ?>">Approve</button>
                                <?php endif ?>
<!--                            --><?php //endif ?>
                            <button type="button" class="btn btn-danger btn-xs btn-delete" data-classroom-id="<?php echo $val->classroom_id; ?>">Delete</button>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="panel-footer clearfix">
        <div class="pull-left">
            <ul class="pagination pagination-sm">
                <?php
                $current = $page->current;
                $start = (ceil($current/10)-1)*10+1;
                $end = $start+9;
                if($end>$page->total_pages) {
                    $end = $page->total_pages;
                }
                ?>
                <?php
                $queryString = $_SERVER['QUERY_STRING'];
                $queryStringArr = explode("&", $queryString);
                $newQueryString = array();
                foreach($queryStringArr as $val) {
                    $valArr = explode("=", $val);
                    if(count($valArr)==2) {
                        if($valArr[0]!='page' and $valArr[0]!='_url') {
                            $newQueryString[] = $val;
                        }
                    }
                }
                $queryString = implode("&", $newQueryString);

                ?>
                <li><a href="?page=1&<?php echo $queryString; ?>">&laquo;</a></li>
                <li><a href="?page=<?php echo $page->before; ?>&<?php echo $queryString; ?>">&lsaquo;</a></li>
                <?php for($i=$start;$i<=$end;$i++) : ?>
                   <li <?php if($i==$current) : ?>class="active"<?php endif ?>><a href="?page=<?php echo $i; ?>&<?php echo $queryString; ?>"><?php echo $i; ?></a></li>
                <?php endfor ?>
                <li><a href="?page=<?php echo $page->next; ?>&<?php echo $queryString; ?>">&rsaquo;</a></li>
                <li><a href="?page=<?php echo $page->last; ?>&<?php echo $queryString; ?>">&raquo;</a></li>
            </ul>
        </div>
        <div class="pull-right">
            <a class="btn btn-default" href="/admin/userClassExcel/">Excel</a>
        </div>

    </div>
</div>