<?php
?>
<ul class="breadcrumb breadcrumb-page">
    <div class="breadcrumb-label text-light-gray">You are here: </div>
    <li><a href="/admin">Home</a></li>
    <li class="active"><a href="/admin/users">Users</a></li>
</ul>
<div class="page-header">

    <div class="row">
        <!-- Page header, center on small screens -->
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-pencil page-header-icon"></i>&nbsp;&nbsp;Users</h1>
    </div>
</div> <!-- / .page-header -->
<div class="panel" id="users">
    <div class="panel-heading">
        <span class="panel-title">List</span>
    </div>

    <div class="panel-body">
        <div class="table-primary table-responsive">
            <table class="table table-striped table-bordered" id="user-table">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Nickname</th>
                    <th>Email</th>
                    <th>Point</th>
                    <th>Country</th>
                    <th>Join Date</th>
                    <th>Login Count</th>
                    <th>Last Login Date</th>
                </tr>
                </thead>
                <tbody>
                <?php $page_count = count($page->items); ?>
                <?php foreach($page->items as $key=>$val) : /** @var $val Classroom */?>
                    <tr>
                        <td><?php echo $page->total_items - $key - (($page->current-1) * $limit); ?></td>
                        <td><button type="button" data-user-id="<?php echo $val->user_id; ?>" class="btn btn-default" data-toggle="modal" data-target="#modal-user-form"><?php echo $val->nickname; ?></button></td>
                        <td><?php echo $val->email; ?></td>
                        <td><?php echo $val->point; ?></td>
                        <td><?php if($val->getCountry()) echo $val->getCountry()->getCountry(); ?></td>
                        <td><?php echo date('m-d-Y',$val->created_at); ?></td>
                        <td>
                            <?php if($val->login_count == 0) : ?>
                                0
                            <?php else : ?>
                                <?php echo $val->login_count; ?>
                            <?php endif ?>
                        </td>
                        <td>
                            <?php if($val->last_login_date == null or $val->last_login_date == 0) : ?>
                                <?php echo date('m-d-Y',$val->created_at); ?>
                            <?php else : ?>
                                <?php echo date('m-d-Y',$val->last_login_date); ?>
                            <?php endif ?>
                        </td>

                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>

        </div>
    </div>

    <div class="panel-footer clearfix">
        <div class="pull-left">
            <ul class="pagination pagination-sm">
                <?php
                $current = $page->current;
                $start = (ceil($current/10)-1)*10+1;
                $end = $start+9;
                if($end>$page->total_pages) {
                    $end = $page->total_pages;
                }
                ?>
                <?php
                $queryString = $_SERVER['QUERY_STRING'];
                $queryStringArr = explode("&", $queryString);
                $newQueryString = array();
                foreach($queryStringArr as $val) {
                    $valArr = explode("=", $val);
                    if(count($valArr)==2) {
                        if($valArr[0]!='page' and $valArr[0]!='_url') {
                            $newQueryString[] = $val;
                        }
                    }
                }
                $queryString = implode("&", $newQueryString);

                ?>
                <li><a href="?page=1&<?php echo $queryString; ?>">&laquo;</a></li>
                <li><a href="?page=<?php echo $page->before; ?>&<?php echo $queryString; ?>">&lsaquo;</a></li>
                <?php for($i=$start;$i<=$end;$i++) : ?>
                    <li <?php if($i==$current) : ?>class="active"<?php endif ?>><a href="?page=<?php echo $i; ?>&<?php echo $queryString; ?>"><?php echo $i; ?></a></li>
                <?php endfor ?>
                <li><a href="?page=<?php echo $page->next; ?>&<?php echo $queryString; ?>">&rsaquo;</a></li>
                <li><a href="?page=<?php echo $page->last; ?>&<?php echo $queryString; ?>">&raquo;</a></li>
            </ul>
        </div>
        <div class="pull-right">
            <a class="btn btn-default" href="/admin/userexcel/">Excel</a>
        </div>
    </div>
</div>

<form class="modal fade" id="modal-user-form" aria-hidden="true" action="/admin/users" method="post" enctype="multipart/form-data">
    <input type="hidden" name="user_id" value="0" />
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">User form</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-xs-12">
                        <label for="user-nickname" class="control-label">Nickname</label>
                        <input type="text" name="nickname" id="user-nickname" value="" class="form-control" />
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <label for="user-email" class="control-label">Email</label>
                        <input type="text" name="email" id="user-email" value="" class="form-control" />
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <label for="user-point" class="control-label">Point</label>
                        <input type="text" name="point" id="user-point" value="" class="form-control" />
                    </div>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="is_admin" id="user-is-admin" value="1" />
                        Admin
                    </label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="btn-user-delete">Unsubscribe</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->