<div id="page-wrapper">

    <section id="two" class="wrapper alt style2">
        <section class="cd-scrolling-bg bg-default">
            <div class="title-wrapper">
                <h3 class="h3 text-center">포트폴리오</h3>
            </div>
            <div class="cd-gallery cd-section cd-container">
                <ul class="grid cs-style-3 clearfix">
                    <li>
                        <figure>
                            <a href="/project/towl/">
                                <img src="/images/towl_thumb.png" alt="list_thumb">
                                <figcaption>
                                    <h3>Traveling Owl</h3>
                                    <em>전문적인 정보와 함께 외국인의 여행을 돕는 서비스</em>
                                    <span class="entypo chevron-right"></span>
                                </figcaption>
                            </a>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <a href="/project/laughingbeans/">
                                <img src="/images/laughingbeans_thumb.jpg" alt="list_thumb">
                                <figcaption>
                                    <h3>Laughing Beans</h3>
                                    <em>외국어와 모국어 서로 교환하여 공부하 플랫폼</em>
                                    <span class="entypo chevron-right"></span>
                                </figcaption>
                            </a>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <a href="/project/enbloom/">
                                <img src="/images/enbloom_thumb.png" alt="list_thumb">
                                <figcaption>
                                    <h3>Enbloom</h3>
                                    <em>고유한 정보로 하나뿐인 심볼을 디자인하는 서비스</em>
                                    <span class="entypo chevron-right"></span>
                                </figcaption>
                            </a>
                        </figure>
                    </li>

                    <li>
                        <figure>
                            <a href="/project/ipoptv/">
                                <img src="/images/ipoptv_thumb.png" alt="list_thumb">
                                <figcaption>
                                    <h3>Ipop tv</h3>
                                    <em>전문적인 정보와 함께 외국인의 여행을 돕는 서비스</em>
                                    <span class="entypo chevron-right"></span>
                                </figcaption>
                            </a>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <a href="/project/gramo/">
                                <img src="/images/gramo_thumb.png" alt="list_thumb">
                                <figcaption>
                                    <h3>Gramo</h3>
                                    <em>광고 적립금을 통한 현금쿠폰 서비스</em>
                                    <span class="entypo chevron-right"></span>
                                </figcaption>
                            </a>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <a href="/project/people/">
                                <img src="/images/people_thumb.png" alt="list_thumb">
                                <figcaption>
                                    <h3>People Fund</h3>
                                    <em> P2P(Peer-to-Peer)대출 서비스</em>
                                    <span class="entypo chevron-right"></span>
                                </figcaption>
                            </a>
                        </figure>
                    </li>
                </ul>
                <div class="more-portfolio text-center">
                    <a href="/portfolio/" class="btn btn-outline">포트폴리오 전체 보기</a>
                </div>
            </div>
        </section> <!-- cd-gallery -->
    </section>
</div>