
<section id="logo">
    <i class="fa fa-rss fa-6"></i>
    <h2>Rss</h2>
</section>

<section class="container">
    <section class="row">
        <form role="login" action="/auth/signUp" method="post" data-success-return-url="/user">
            <div class="form-group">
                <input type="text" name="email" placeholder="Enter your email" required class="form-control" />
                <span class="glyphicon glyphicon-user"></span>
            </div>

            <div class="form-group">
                <input type="password" name="password" placeholder="Enter password" required class="form-control" />
                <span class="glyphicon glyphicon-lock"></span>
            </div>

            <div class="form-group">
                <input type="checkbox" name="remember" value="1" /> Remember me
            </div>

            <button type="button" name="go" class="btn btn-block btn-primary">Sign up Now</button>

            <section>
                <a class="pull-left" href="/user/singup" >Sign up</a>
                <a class="pull-right" href="#">Forgot your password ?</a>
            </section>
        </form>
    </section>
</section>
