
<!--[if lte IE 8]><script src="/js/ie/html5shiv.js"></script><![endif]-->


<!-- Page Wrapper -->
<div id="page-wrapper">

    <!-- Header -->
<!--    <header id="header" class="alt">-->
<!--        <h1><a href="index.html">Jay</a></h1>-->
<!--        <nav id="nav">-->
<!--            <ul>-->
<!--                <li class="special">-->
<!--                    <a href="#menu" class="menuToggle"><span>Menu</span></a>-->
<!--                    <div id="menu">-->
<!--                        <ul>-->
<!--                            <li><a href="index.html">Home</a></li>-->
<!--                            <li><a href="generic.html">Generic</a></li>-->
<!--                            <li><a href="elements.html">Elements</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </nav>-->
<!--    </header>-->

    <!-- Banner -->
    <section id="banner">
        <div class="inner">
            <h2>패왕색</h2>
            <p>어깨성애자를 패기로 쓰러트린자!<br />
                견문색과 무장색을 겸비하여 상대의 복통을 유발하는자!<br />
                <a href="http://html5up.net">슈가보이~</a>.</p>
                <img class="user-avatar" src="/images/profile.png" alt="user profile image">
        </div>
        <a href="#one" class="more scrolly">Learn More</a>
    </section>

    <!-- One -->
    <section id="one" class="wrapper style1 special">
        <div class="inner">
            <header class="major">
                <h2>ABOUT JAY</h2>
                <p> 현승재. 영어 이름이 JAY입니다. <br>
                    필드에서 개발자로 일하면서 제게 필요한, 그리고 재미있는 컨셉의 서비스를 개발하는것을 좋아합니다. <br>
                    주로 개발되는 서비스의 환경은 web 기반의 front-end, back-end를 총괄할 수 있습니다. <br>
                    IT관련 블로그를 운영하며, opensource에도 참여중입니다. <br>
                    No Warning, No Error를 통하여 Warning없이 작성하여 Error가 없는 프로그램을 만드는것을 목표로 합니다.<br>
                    앞으로도 재미있고 더욱 필요한 서비스들을 계속해서 만들어나갈 생각입니다.</p>
            </header>
            <ul class="icons major">
                <li><span class="icon fa-rocket major style1"><span class="label">Lorem</span></span></li>
                <li><span class="icon fa-subscript major style2"><span class="label">Ipsum</span></span></li>
                <li><span class="icon fa-code major style3"><span class="label">Dolor</span></span></li>
            </ul>
        </div>
    </section>

    <!-- Two -->
    <section id="two" class="wrapper alt style2">
        <section class="cd-scrolling-bg bg-default">
            <div class="title-wrapper">
                <h3 class="h3 text-center">주요 포트폴리오</h3>
            </div>
            <div class="cd-gallery cd-section cd-container">
                <ul class="grid cs-style-3 clearfix">
                    <li>
                        <figure>
                            <a href="/project/towl/">
                                <img src="/images/towl_thumb.png" alt="list_thumb">
                                <figcaption>
                                    <h3>Traveling Owl</h3>
                                    <em>전문적인 정보와 함께 외국인의 여행을 돕는 서비스</em>
                                    <span class="entypo chevron-right"></span>
                                </figcaption>
                            </a>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <a href="/project/laughingbeans/">
                                <img src="/images/laughingbeans_thumb.jpg" alt="list_thumb">
                                <figcaption>
                                    <h3>Laughing Beans</h3>
                                    <em>외국어와 모국어 서로 교환하여 공부하 플랫폼</em>
                                    <span class="entypo chevron-right"></span>
                                </figcaption>
                            </a>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <a href="/project/enbloom/">
                                <img src="/images/enbloom_thumb.png" alt="list_thumb">
                                <figcaption>
                                    <h3>Enbloom</h3>
                                    <em>고유한 정보로 하나뿐인 심볼을 디자인하는 서비스</em>
                                    <span class="entypo chevron-right"></span>
                                </figcaption>
                            </a>
                        </figure>
                    </li>
                </ul>
                <div class="more-portfolio text-center">
                    <a href="/projects/" class="btn btn-outline">포트폴리오 전체 보기</a>
                </div>
            </div>
        </section> <!-- cd-gallery -->
    </section>

    <!-- Three -->
    <section id="three" class="wrapper style3 special">
        <div class="inner">
            <header class="major">
                <h2>Use Skill</h2>

            </header>
            <ul class="features">
                <li class="icon fa-file-code-o">
                    <h3>Front-end</h3>
                    <p>HTML/CSS+Bootstrap<br>
                        script+jquery</p>
                </li>
                <li class="icon fa-laptop">
                    <h3>Bank-end</h3>
                    <p>linux+ubuntu, windows+window server<br>
                        java+spring+ibatis<br>
                        python+django<br>
                        php+phalcon/XE/Wordpress<br>
                        nodejs+express+socketIO<br>
                    </p>
                </li>

                <li class="icon fa-sitemap">
                    <h3>Data Bases</h3>
                    <p>mysql, oracle, mongodb<br>
                        RDB tuning
                    </p>
                </li>
                <li class="icon fa-line-chart">
                    <h3>Etc.</h3>
                    <p>Math+Graph+2D/3D<br>
                        Machine Learning/Artificial Neural Network<br>
                        c/c++/ncs/winapi/MFC/boost<br>
                        hadoop
                    </p>
                </li>

            </ul>
        </div>
    </section>

    <!-- CTA -->
<!--    <section id="cta" class="wrapper style4">-->
<!--        <div class="inner">-->
<!--            <header>-->
<!--                <h2>Arcue ut vel commodo</h2>-->
<!--                <p>Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla.</p>-->
<!--            </header>-->
<!--            <ul class="actions vertical">-->
<!--                <li><a href="#" class="button fit special">Activate</a></li>-->
<!--                <li><a href="#" class="button fit">Learn More</a></li>-->
<!--            </ul>-->
<!--        </div>-->
<!--    </section>-->

    <!-- Footer -->
    <footer id="footer">
        <h3>CONTACT ME</h3>
        <ul class="icons">
            <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
            <li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
            <li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
        </ul>
        <ul class="copyright">
            <li>&copy; Untitled</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
    </footer>

</div>

<!-- Scripts -->
<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.scrollex.min.js"></script>
<script src="/js/jquery.scrolly.min.js"></script>
<script src="/js/skel.min.js"></script>
<script src="/js/util.js"></script>
<!--[if lte IE 8]><script src="/js/ie/respond.min.js"></script><![endif]-->
<script src="/js/main.js"></script>

