<?php

?>
<!DOCTYPE html>


<!--[if IE 8]>         <html class="ie8"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Laughing beans admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

    <!-- Open Sans font from Google CDN -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">

    <!-- Pixel Admin's stylesheets -->
    <link href="/pixeladmin/stylesheets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/pixeladmin/stylesheets/pixel-admin.min.css" rel="stylesheet" type="text/css">
    <link href="/pixeladmin/stylesheets/widgets.min.css" rel="stylesheet" type="text/css">
    <link href="/pixeladmin/stylesheets/rtl.min.css" rel="stylesheet" type="text/css">
    <link href="/pixeladmin/stylesheets/themes.min.css" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
    <script src="/pixeladmin/javascripts/ie.min.js"></script>
    <![endif]-->
</head>


<body class="theme-default main-menu-animated">

<script>var init = [];</script>

<div id="main-wrapper">


    <!-- 2. $MAIN_NAVIGATION ===========================================================================
    
        Main navigation
    -->
    <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
        <!-- Main menu toggle -->
        <button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>

        <div class="navbar-inner">
            <!-- Main navbar header -->
            <div class="navbar-header">

                <!-- Logo -->
                <a href="/admin/" class="navbar-brand">
                    <!--<div><img alt="Pixel Admin" src="/pixeladmin/images/pixel-admin/main-navbar-logo.png"></div>-->
                    Laughing Beans
                </a>

                <!-- Main navbar toggle -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

            </div> <!-- / .navbar-header -->

            <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
                <div>

                    <div class="right clearfix">
                        <ul class="nav navbar-nav pull-right right-navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
                                    <span>test</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="/auth/logout"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
                                </ul>
                            </li>
                        </ul> <!-- / .navbar-nav -->
                    </div> <!-- / .right -->
                </div>
            </div> <!-- / #main-navbar-collapse -->
        </div> <!-- / .navbar-inner -->
    </div> <!-- / #main-navbar -->
    <!-- /2. $END_MAIN_NAVIGATION -->
    <div id="main-menu" role="navigation">
        <div id="main-menu-inner">
            <ul class="navigation">
                <li>
                    <a href="/admin"><i class="menu-icon fa fa-video-camera"></i><span class="mm-text">Video</span></a>
                </li>
                <li>
                    <a href="/admin/userClass"><i class="menu-icon fa fa-pencil"></i><span class="mm-text">User class</span></a>
                </li>
                <li>
                    <a href="/admin/users"><i class="menu-icon fa fa-users"></i><span class="mm-text">Users</span></a>
                </li>
                <li>
                    <a href="/admin/language"><i class="menu-icon fa fa-language"></i><span class="mm-text">Language</span></a>
                </li>
                <li>
                    <a href="/admin/interest"><i class="menu-icon fa fa-bars"></i><span class="mm-text">Category</span></a>
                </li>
            </ul>
        </div> <!-- / #main-menu-inner -->
    </div> <!-- / #main-menu -->
    <!-- /4. $MAIN_MENU -->

    <div id="content-wrapper">
        <?php echo $this->getContent(); ?>
    </div> <!-- / #content-wrapper -->
    <div id="main-menu-bg"></div>
</div> <!-- / #main-wrapper -->

<!-- Get jQuery from Google CDN -->
<!--[if !IE]> -->
<script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js">'+"<"+"/script>"); </script>
<!-- <![endif]-->
<!--[if lte IE 9]>
<script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">'+"<"+"/script>"); </script>
<![endif]-->


<!-- Pixel Admin's javascripts -->
<script src="/pixeladmin/javascripts/bootstrap.min.js"></script>
<script src="/pixeladmin/javascripts/pixel-admin.min.js"></script>
<script src="/js/jquery.form.min.js"></script>
<script src="/js/admin.js"></script>
<script src="//cdn.datatables.net/tabletools/2.2.1/js/dataTables.tableTools.min.js"></script>

<script type="text/javascript">
    init.push(function () {
        // Javascript code here
    })
    window.PixelAdmin.start(init);
</script>

</body>
</html>